CREATE TABLE CONTATTO (
    ID SERIAL,
    FOTO VARCHAR(200) DEFAULT NULL,
    NOME VARCHAR(20) NOT NULL,
    COGNOME VARCHAR(20) NOT NULL,
    SECURITY BOOLEAN DEFAULT FALSE,

    PRIMARY KEY(ID)
);

CREATE TABLE GRUPPO (
    NOME VARCHAR(50),

    PRIMARY KEY(NOME)
);

CREATE TABLE PARTECIPAZIONE (
    ID_CONTATTO INTEGER NOT NULL,
    NOME_GRUPPO VARCHAR(50) NOT NULL,

	PRIMARY KEY(ID_CONTATTO, NOME_GRUPPO),
    FOREIGN KEY(ID_CONTATTO) REFERENCES CONTATTO(ID),
    FOREIGN KEY(NOME_GRUPPO) REFERENCES GRUPPO(NOME)
);

CREATE TABLE SISTEMA_DI_MESSAGING (
    USERNAME VARCHAR(50),
    SERVIZIO VARCHAR(10),
    STATO VARCHAR(100),
    EMAIL_USERNAME VARCHAR(50) NOT NULL,
    EMAIL_DOMINIO VARCHAR(30) NOT NULL,
    ID_CONTATTO INTEGER NOT NULL,

    PRIMARY KEY(USERNAME, SERVIZIO),
    FOREIGN KEY(ID_CONTATTO) REFERENCES CONTATTO(ID),
    FOREIGN KEY(EMAIL_USERNAME, EMAIL_DOMINIO) REFERENCES EMAIL(USERNAME, DOMINIO),

    CONSTRAINT check_servizi
    CHECK (SERVIZIO IN ('Messenger', 'Signal', 'Skype', 'Teams', 'Telegram', 'Viber', 'WeChat', 'Whatsapp'))
);

CREATE TABLE EMAIL (
    USERNAME VARCHAR(50),
    DOMINIO VARCHAR(30),
    ID_CONTATTO INTEGER NOT NULL,

    PRIMARY KEY(USERNAME, DOMINIO),
    FOREIGN KEY(ID_CONTATTO) REFERENCES CONTATTO(ID)
);

CREATE TABLE INDIRIZZO_PRINCIPALE (
    ID SERIAL,
    VIA VARCHAR(50) NOT NULL,
    CIVICO INTEGER NOT NULL,
    CITTA VARCHAR(50) NOT NULL,
    CAP VARCHAR(12) NOT NULL,
    NAZIONE VARCHAR(60) NOT NULL,
    ID_CONTATTO INTEGER NOT NULL,

    PRIMARY KEY(ID),
    FOREIGN KEY(ID_CONTATTO) REFERENCES CONTATTO(ID)
);

CREATE TABLE INDIRIZZO_SECONDARIO (
    ID SERIAL,
    VIA VARCHAR(50) NOT NULL,
    CIVICO INTEGER NOT NULL,
    CITTA VARCHAR(50) NOT NULL,
    CAP VARCHAR(12) NOT NULL,
    NAZIONE VARCHAR(60) NOT NULL,
    ID_CONTATTO INTEGER NOT NULL,

    PRIMARY KEY(ID),
    FOREIGN KEY(ID_CONTATTO) REFERENCES CONTATTO(ID)
);

CREATE TABLE NUMERO_FISSO (
    PREFISSO VARCHAR(5),
    NUMERO VARCHAR(10),
    ID_CONTATTO INTEGER NOT NULL,

    PRIMARY KEY(PREFISSO, NUMERO, ID_CONTATTO),
    FOREIGN KEY(ID_CONTATTO) REFERENCES CONTATTO(ID)
);

CREATE TABLE NUMERO_MOBILE (
    PREFISSO VARCHAR(5),
    NUMERO VARCHAR(10),
    ID_CONTATTO INTEGER NOT NULL,

    PRIMARY KEY(PREFISSO, NUMERO),
    FOREIGN KEY(ID_CONTATTO) REFERENCES CONTATTO(ID)
);

CREATE TABLE REINDIRIZZAMENTO (
    PREFISSO_FISSO VARCHAR(5) NOT NULL,
    NUMERO_FISSO VARCHAR(10) NOT NULL,
    ID_CONTATTO_FISSO INTEGER NOT NULL,
    PREFISSO_MOBILE VARCHAR(5) NOT NULL,
    NUMERO_MOBILE VARCHAR(10) NOT NULL,

	PRIMARY KEY(PREFISSO_FISSO, NUMERO_FISSO, ID_CONTATTO_FISSO, PREFISSO_MOBILE, NUMERO_MOBILE),
    FOREIGN KEY(PREFISSO_FISSO, NUMERO_FISSO, ID_CONTATTO_FISSO) REFERENCES NUMERO_FISSO(PREFISSO, NUMERO, ID_CONTATTO),
    FOREIGN KEY(PREFISSO_MOBILE, NUMERO_MOBILE) REFERENCES NUMERO_MOBILE(PREFISSO, NUMERO)
);