insert into indirizzo_principale (via, civico, citta, cap, nazione, id_contatto) values ('Norway Maple', 62, 'Miaoling', 65186, 'China', 1);
insert into indirizzo_principale (via, civico, citta, cap, nazione, id_contatto) values ('Kim', 56, 'Limboto', 19343, 'Indonesia', 2);
insert into indirizzo_principale (via, civico, citta, cap, nazione, id_contatto) values ('Sunbrook', 82, 'Damai', 76040, 'China', 3);
insert into indirizzo_principale (via, civico, citta, cap, nazione, id_contatto) values ('Grover', 77, 'Thomastown', 30386, 'Ireland', 4);
insert into indirizzo_principale (via, civico, citta, cap, nazione, id_contatto) values ('Hazelcrest', 98, 'Buy', 23282, 'Russia', 5);
insert into indirizzo_principale (via, civico, citta, cap, nazione, id_contatto) values ('Lakeland', 60, 'Paris 16', 10167, 'France', 6);
insert into indirizzo_principale (via, civico, citta, cap, nazione, id_contatto) values ('Judy', 70, 'Hujra', 38421, 'Pakistan', 7);
insert into indirizzo_principale (via, civico, citta, cap, nazione, id_contatto) values ('Roth', 41, 'Tembeling', 40506, 'Indonesia', 8);
insert into indirizzo_principale (via, civico, citta, cap, nazione, id_contatto) values ('Thierer', 2, 'Xingzhen', 36600, 'China', 9);
insert into indirizzo_principale (via, civico, citta, cap, nazione, id_contatto) values ('Kipling', 3, 'Qila Abdullāh', 60829, 'Pakistan', 10);
insert into indirizzo_principale (via, civico, citta, cap, nazione, id_contatto) values ('Kropf', 82, 'Puolanka', 29085, 'Finland', 11);
insert into indirizzo_principale (via, civico, citta, cap, nazione, id_contatto) values ('2nd', 41, 'Mae Wang', 76209, 'Thailand', 12);
insert into indirizzo_principale (via, civico, citta, cap, nazione, id_contatto) values ('Novick', 100, 'Baishi', 56232, 'China', 13);
insert into indirizzo_principale (via, civico, citta, cap, nazione, id_contatto) values ('Lakewood', 85, 'Пласница', 76386, 'Macedonia', 14);
insert into indirizzo_principale (via, civico, citta, cap, nazione, id_contatto) values ('Judy', 34, 'Vin’kivtsi', 50132, 'Ukraine', 15);
insert into indirizzo_principale (via, civico, citta, cap, nazione, id_contatto) values ('Waywood', 80, 'Lattes', 45556, 'France', 16);
insert into indirizzo_principale (via, civico, citta, cap, nazione, id_contatto) values ('Maple', 48, 'Dopang', 67603, 'Indonesia', 17);
insert into indirizzo_principale (via, civico, citta, cap, nazione, id_contatto) values ('Hoard', 8, 'Chak Two Hundred Forty-Nine TDA', 14739, 'Pakistan', 18);
insert into indirizzo_principale (via, civico, citta, cap, nazione, id_contatto) values ('Pond', 29, 'Itaperuçu', 25283, 'Brazil', 19);
insert into indirizzo_principale (via, civico, citta, cap, nazione, id_contatto) values ('Red Cloud', 68, 'Xiting', 74276, 'China', 20);
insert into indirizzo_principale (via, civico, citta, cap, nazione, id_contatto) values ('6th', 31, 'Zhengcun', 11141, 'China', 21);
insert into indirizzo_principale (via, civico, citta, cap, nazione, id_contatto) values ('Gale', 19, 'Marabá', 95452, 'Brazil', 22);
insert into indirizzo_principale (via, civico, citta, cap, nazione, id_contatto) values ('Rowland', 23, 'Camacha', 49261, 'Portugal', 23);
insert into indirizzo_principale (via, civico, citta, cap, nazione, id_contatto) values ('Eggendart', 20, 'Alegria', 63153, 'Philippines', 24);
insert into indirizzo_principale (via, civico, citta, cap, nazione, id_contatto) values ('Red Cloud', 24, 'Matsuyama', 89425, 'Japan', 25);
insert into indirizzo_principale (via, civico, citta, cap, nazione, id_contatto) values ('Westport', 52, 'Bagulin', 31912, 'Philippines', 26);
insert into indirizzo_principale (via, civico, citta, cap, nazione, id_contatto) values ('Kedzie', 90, 'Berck', 87955, 'France', 27);
insert into indirizzo_principale (via, civico, citta, cap, nazione, id_contatto) values ('Mitchell', 100, 'Bulangan', 37223, 'Indonesia', 28);
insert into indirizzo_principale (via, civico, citta, cap, nazione, id_contatto) values ('Londonderry', 97, 'Saint-Maur-des-Fossés', 45251, 'France', 29);
insert into indirizzo_principale (via, civico, citta, cap, nazione, id_contatto) values ('Bartelt', 57, 'Huoxian', 83764, 'China', 30);
insert into indirizzo_principale (via, civico, citta, cap, nazione, id_contatto) values ('Old Shore', 58, 'Miandrivazo', 81491, 'Madagascar', 31);
insert into indirizzo_principale (via, civico, citta, cap, nazione, id_contatto) values ('Dawn', 61, 'Sunzhuang', 74056, 'China', 32);
insert into indirizzo_principale (via, civico, citta, cap, nazione, id_contatto) values ('Collingwood Rd ', 10, 'Newton-Le-Willows', 'WA12', 'England', 33)
insert into indirizzo_principale (via, civico, citta, cap, nazione, id_contatto) values ('Del Sol', 98, 'Matozinhos', 21605, 'Brazil', 34);
insert into indirizzo_principale (via, civico, citta, cap, nazione, id_contatto) values ('Lyons', 15, 'Monze', 80377, 'Zambia', 35);
insert into indirizzo_principale (via, civico, citta, cap, nazione, id_contatto) values ('Ridgeview', 6, 'Chenjiahe', 46902, 'China', 36);
insert into indirizzo_principale (via, civico, citta, cap, nazione, id_contatto) values ('Pankratz', 70, 'Putrajaya', 53251, 'Malaysia', 37);
insert into indirizzo_principale (via, civico, citta, cap, nazione, id_contatto) values ('Union', 31, 'Mainque', 84238, 'Argentina', 38);
insert into indirizzo_principale (via, civico, citta, cap, nazione, id_contatto) values ('Service', 79, 'La Soledad', 58443, 'Mexico', 39);
insert into indirizzo_principale (via, civico, citta, cap, nazione, id_contatto) values ('Merchant', 72, 'Dalubian', 14548, 'China', 40);
insert into indirizzo_principale (via, civico, citta, cap, nazione, id_contatto) values ('Truax', 54, 'Kairouan', 43043, 'Tunisia', 41);
insert into indirizzo_principale (via, civico, citta, cap, nazione, id_contatto) values ('8th', 52, 'Halmstad', 36928, 'Sweden', 42);
insert into indirizzo_principale (via, civico, citta, cap, nazione, id_contatto) values ('Glacier Hill', 28, 'Cibitung', 55035, 'Indonesia', 43);
insert into indirizzo_principale (via, civico, citta, cap, nazione, id_contatto) values ('Cambridge', 21, 'Lingda', 21129, 'China', 44);
insert into indirizzo_principale (via, civico, citta, cap, nazione, id_contatto) values ('Fairview', 11, 'Dijon', 11952, 'France', 45);
insert into indirizzo_principale (via, civico, citta, cap, nazione, id_contatto) values ('Parkside', 72, 'Hobart', 82343, 'Australia', 46);
insert into indirizzo_principale (via, civico, citta, cap, nazione, id_contatto) values ('Erie', 73, 'Ráječko', 68286, 'Czech Republic', 47);
insert into indirizzo_principale (via, civico, citta, cap, nazione, id_contatto) values ('Waywood', 71, 'Merritt', 15997, 'Canada', 48);
insert into indirizzo_principale (via, civico, citta, cap, nazione, id_contatto) values ('Meadow Valley', 73, 'Katoro', 15586, 'Tanzania', 49);
insert into indirizzo_principale (via, civico, citta, cap, nazione, id_contatto) values ('Arkansas', 82, 'Az Zawr', 52395, 'Kuwait', 50);